# Generated by Django 5.1.3 on 2024-12-01 20:39

import habits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="location",
            field=models.CharField(
                default="В квартире",
                max_length=200,
                verbose_name="Место выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=habits.models.CustomDateTimeField(
                default="2024-12-01 20:39",
                help_text="Введите дату YYYY-MM-DD HH:MM",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
