# Generated by Django 5.1.3 on 2024-12-01 23:18

from django.db import migrations

import habits.models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_location_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=habits.models.CustomDateTimeField(
                default="2024-12-01 23:18",
                help_text="Введите дату YYYY-MM-DD HH:MM",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
