# Generated by Django 5.1.3 on 2024-12-08 16:26

import habits.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=habits.models.CustomDateTimeField(
                default="2024-12-08 16:25",
                help_text="Введите дату YYYY-MM-DD HH:MM",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
