# Generated by Django 5.1.3 on 2024-12-08 23:44

import habits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Периодичность выполнения привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=habits.models.CustomDateTimeField(
                default="2024-12-08 23:44",
                help_text="Введите дату YYYY-MM-DD HH:MM",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
